### PR TITLE
async pathfinding: fix path race condition

### LINKED ISSUE #604: Entity threw exception (ConcurrentModificationException). Async pathfinding bug?
### Checklist

- [x] I have searched the existing issues and the documentation
- [ ] I ticked all the boxes without actually reading them
- [x] I am using latest Leaf build from https://www.leafmc.one/download
- [x] I tested and couldn't replicate this issue on latest [Paper](https://papermc.io/downloads/paper) or [Purpur](https://purpurmc.org/download/purpur) build

### What behaviour is observed?

errors in console

### What is the expected behavior?

no errors

### How to reproduce?

Check https://mclo.gs/YIZ4w9c

[leaf-global.yml.txt](https://github.com/user-attachments/files/24782214/leaf-global.yml.txt)
[paper-global.yml.txt](https://github.com/user-attachments/files/24782215/paper-global.yml.txt)

### Spark profiler link

Unable to use spark without VPN (time out)

### Error log (if applicable)

https://mclo.gs/YIZ4w9c

### PR DESCRIPTION
**Pull request by hayanesuru**
#519 #589

Closed #604

### CODE REVIEW

File: leaf-server/src/main/java/org/dreeam/leaf/async/path/AsyncPath.java [hunk 1]
```diff
@@ -1,54 +1,36 @@
...
-     */
-    private volatile boolean ready = false;
+    private boolean ready = false;
 
-    /**
-     * Runnable waiting for this to be processed
-     * ConcurrentLinkedQueue is thread-safe, non-blocking and non-synchronized
-     */
-    private final ConcurrentLinkedQueue<Runnable> postProcessing = new ConcurrentLinkedQueue<>();
+    private final ArrayList<Consumer<Path>> postProcessing = new ArrayList<>();
```
Comment (MartijnMuijsers) [inline leaf-server/src/main/java/org/dreeam/leaf/async/path/AsyncPath.java:24]: Good change!

File: leaf-server/src/main/java/org/dreeam/leaf/async/path/AsyncPath.java [hunk 2]
```diff
@@ -1,54 +1,36 @@
...
 
-    /**
-     * The supplier of the real processed path
-     */
-    private final Supplier<Path> pathSupplier;
-
-    /*
-     * Processed values
-     */
+    private @Nullable Supplier<Path> task;
```
Comment (MartijnMuijsers) [inline leaf-server/src/main/java/org/dreeam/leaf/async/path/AsyncPath.java]: Good change! Helps reclaim memory faster

File: leaf-server/src/main/java/org/dreeam/leaf/async/path/AsyncPath.java [hunk 3]
```diff
@@ -176,6 +143,13 @@ public boolean canReach() {
 
     @Override
     public boolean isDone() {
+        boolean ready = this.ready;
+        if (!ready) {
+            Path ret = this.ret;
+            if (ret != null) {
+                complete(ret);
```
Comment (MartijnMuijsers) [inline leaf-server/src/main/java/org/dreeam/leaf/async/path/AsyncPath.java]: If two threads call `isDone` at the same time, they will both run `complete`. That's bad

Comment (MartijnMuijsers) [inline leaf-server/src/main/java/org/dreeam/leaf/async/path/AsyncPath.java:158]: If this path is only completed upon `isDone`, what happens upon `isProcessed`? Shoud it also call `complete`?

I assume `isDone()` and `isProcessed()` can only be run from the main thread, right?

File: leaf-server/src/main/java/org/dreeam/leaf/async/path/AsyncPath.java [hunk 4]
```diff
@@ -105,47 +83,36 @@ public final void schedulePostProcessing(Runnable runnable) {
...
-            return false;
-        }
-
-        // For single position (common case), do direct comparison
-        if (positions.size() == 1) { // Both have the same size at this point
-            return this.positions.iterator().next().equals(positions.iterator().next());
-        }
-
-        return this.positions.containsAll(positions);
+        return this.positions.equals(positions);
```
Comment (MartijnMuijsers) [inline leaf-server/src/main/java/org/dreeam/leaf/async/path/AsyncPath.java:94]: Original is `containsAll`, this changes actual behavior

File: leaf-server/src/main/java/org/dreeam/leaf/async/path/AsyncPath.java (hunk 1 above)
Comment (MartijnMuijsers) [reply leaf-server/src/main/java/org/dreeam/leaf/async/path/AsyncPath.java:24]: I'm assuming `schedulePostProcessing` is only called from the main thread, correct? Otherwise the `.add` will cause issues when called from multiple threads

File: leaf-server/src/main/java/org/dreeam/leaf/async/path/AsyncPath.java [hunk 5]
```diff
@@ -87,14 +68,11 @@ public boolean isProcessed() {
...
      * Returns the future representing the processing state of this path
      */
-    public final void schedulePostProcessing(Runnable runnable) {
+    public final void schedulePostProcessing(Consumer<Path> runnable) {
         if (this.ready) {
-            runnable.run();
+            runnable.accept(this);
         } else {
-            this.postProcessing.offer(runnable);
-            if (this.ready) {
```
Comment (MartijnMuijsers) [inline leaf-server/src/main/java/org/dreeam/leaf/async/path/AsyncPath.java:95]: This is actually necessary, otherwise:

Thread 1 calls `schedulePostProcessing` and checks `this.ready`, it is false
Thread 2 calls `complete` and does:
```
this.ready = true;
for (Consumer<Path> consumer : this.postProcessing) {
    consumer.accept(this);
}
this.postProcessing.clear();
```
Thread 1 then does `this.postProcessing.add(runnable)` and the runnable is never executed.

**Review by MartijnMuijsers — CHANGES_REQUESTED** [review]
.

File: leaf-server/src/main/java/org/dreeam/leaf/async/path/AsyncPathProcessor.java [hunk 6]
```diff
@@ -67,7 +67,7 @@ protected static CompletableFuture<Void> queue(AsyncPath path) {
      */
     public static void awaitProcessing(@Nullable Path path, Consumer<@Nullable Path> afterProcessing) {
```
Comment (MartijnMuijsers) [inline leaf-server/src/main/java/org/dreeam/leaf/async/path/AsyncPathProcessor.java:68]: This already existed in the original, but the name `await` here is not really correct. `applyAfterProcessing`?

File: leaf-server/src/main/java/org/dreeam/leaf/async/path/AsyncPath.java [hunk 7]
```diff
@@ -72,11 +54,10 @@ public class AsyncPath extends Path {
     public AsyncPath(List<Node> emptyNodeList, Set<BlockPos> positions, Supplier<Path> pathSupplier) {
         super(emptyNodeList, null, false);
 
-        this.nodes = emptyNodeList;
         this.positions = positions;
-        this.pathSupplier = pathSupplier;
+        this.task = pathSupplier;
 
-        AsyncPathProcessor.queue(this);
+        AsyncPathProcessor.queue(() -> this.ret = pathSupplier.get());
```
Comment (MartijnMuijsers) [inline leaf-server/src/main/java/org/dreeam/leaf/async/path/AsyncPath.java]: Can we change this to:

```java
() -> {
    if (this.ret == null) {
        this.ret = pathSupplier.get();
    }
}
```

The `this.ret == null` is only a heuristic that may lead us to skip this if the main thread did it in `process` before the `AsyncPathProcessor` got to it

File: leaf-server/src/main/java/org/dreeam/leaf/async/path/AsyncPath.java [hunk 8]
```diff
@@ -105,47 +83,36 @@ public final void schedulePostProcessing(Runnable runnable) {
...
-        Runnable runnable;
-        while ((runnable = this.postProcessing.poll()) != null) {
-            if (isTickThread) {
-                runnable.run();
-            } else {
-                MinecraftServer.getServer().scheduleOnMain(runnable);
-            }
+        final Path ret = this.ret;
+        final Supplier<Path> task = this.task;
+        final Path bestPath = ret != null ? ret : Objects.requireNonNull(task).get();
```
Comment (MartijnMuijsers) [inline leaf-server/src/main/java/org/dreeam/leaf/async/path/AsyncPath.java]:
```suggestion
        final Path bestPath = ret != null ? ret : (this.ret = Objects.requireNonNull(task).get());
```

So that we can use the heuristic I mentioned above ^

**Review by MartijnMuijsers — APPROVED** [review]

**Review by Dreeam-qwq — APPROVED** [review]
Nice PR! Thanks~
